addons:
  sonarcloud:
    organization: "henryssondaniel-github"
    token: $SONAR_TOKEN
language: node_js
matrix:
  include:
    - node_js: "6"
      env: FULL_RUN=false
    - node_js: "7"
      env: FULL_RUN=false
    - node_js: "8"
      env: FULL_RUN=false
    - node_js: "9"
      env: FULL_RUN=false
    - node_js: "10"
      env: FULL_RUN=false
    - node_js: "11"
      env: FULL_RUN=false
    - node_js: "12"
      env: FULL_RUN=true
script:
  - if [ "$FULL_RUN" != "false" ]; then sonar-scanner; fi